### ISSUE TITLE
Add an output filename option...

### ISSUE THREAD

**Issue by ocefpaf** [conda-incubator/conda-lock#10]
... and change the default to be `conda-{envname}-{platforme}.lock`.

**Comment by scottyhq** [comment]
@ocefpaf - this would be useful (`conda-lock -f environment.yml -p linux-64 -o packages.txt`). 

another consideration for default would `spec-file-{envname}-{platform}.txt` to align with conda documentation?
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments

**Comment by ocefpaf** [comment]
I have some commits here that I've been meaning to push. PR soon.

**Comment by mariusvniekerk** [comment]
This has now been implemented in the 0.8.0 release
