### ISSUE TITLE
Unable to create lock with cuda package(s) from a Mac

### ISSUE THREAD

**Issue by hajapy** [conda-incubator/conda-lock#101]
This environment can generate a valid lock on a linux machine but not on a mac. I'm not exactly sure if this is a conda-lock or mamba/conda issue related to virtual packages and cuda support, but did find it surprising not to be able to generate the linux lock from a mac in this case (one of the really nice features of conda-lock). 

Linux:

```
cat cuda-constrained.yaml
name: cuda
channels:
  - conda-forge
dependencies:
  - cudatoolkit =11.0
  - cudnn =8.0

conda-lock lock --mamba -f cuda-constrained.yaml -p linux-64 --filename-template 'cuda-constrained.lock'

cat cuda-constrained.lock
# platform: linux-64
# env_hash: 231edd623703d47e04a863c039244ba0f9e29e4dcd36589dd12e3052e58bb6c7
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2#d7c89558ba9fa0495403155b64376d81
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-11.1.0-h56837e0_6.tar.bz2#a7420de095361151e2a4d2687ad39292
https://conda.anaconda.org/conda-forge/linux-64/libgomp-11.1.0-hc902ee8_6.tar.bz2#4643448d355a09dd587ffd8838acf8e3
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_gnu.tar.bz2#561e277319a41d4f24f5c05a9ef63c04
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-11.1.0-hc902ee8_6.tar.bz2#3dbb18ea1f6e616bc59d7b51640d2af1
https://conda.anaconda.org/conda-forge/linux-64/cudatoolkit-11.0.3-h15472ef_8.tar.bz2#afed8db569f6974fdcd5e9f362985bf2
https://conda.anaconda.org/conda-forge/linux-64/cudnn-8.0.5.39-ha5ca753_1.tar.bz2#8a89f290d4175f8f11c5ddba81fd16d6
```

Mac:

```
Mac OS

conda-lock lock --mamba -f cuda-constrained.yaml -p linux-64 --filename-template 'cuda-constrained.lock'
generating lockfile for linux-64
Could not solve for lock
    Command: ['mamba', 'create', '--prefix', '/var/folders/m0/7xmfqfjn1l9btlt1m971ldz80000gp/T/tmpk511_yer/prefix', '--dry-run', '--json', '--override-channels', '--channel', 'conda-forge', 'cudnn =8.0', 'cudatoolkit =11.0']
    STDOUT:
Encountered problems while solving.
Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by cudnn-8.0.5.39-h01f27c4_1
Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by cudatoolkit-11.0.3-h15472ef_6
```

If I unconstrain the cudnn and cudatoolkit versions, it can solve on mac, but only for old versions:

```
cat cuda-unconstrained.yaml
name: cuda
channels:
  - conda-forge
dependencies:
  - cudatoolkit
  - cudnn

conda-lock lock --mamba -f cuda-unconstrained.yaml -p linux-64 --filename-template 'cuda-unconstrained.lock'

cat cuda-unconstrained.lock
# platform: linux-64
# env_hash: 9dff44ba64e18168663ddb810849ebe8ea25f234505d51f4c27183f6b8d297a6
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2#d7c89558ba9fa0495403155b64376d81
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-11.1.0-h56837e0_6.tar.bz2#a7420de095361151e2a4d2687ad39292
https://conda.anaconda.org/conda-forge/linux-64/libgomp-11.1.0-hc902ee8_6.tar.bz2#4643448d355a09dd587ffd8838acf8e3
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_gnu.tar.bz2#561e277319a41d4f24f5c05a9ef63c04
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-11.1.0-hc902ee8_6.tar.bz2#3dbb18ea1f6e616bc59d7b51640d2af1
https://conda.anaconda.org/conda-forge/linux-64/cudatoolkit-10.2.89-h8f6ccaa_8.tar.bz2#fbfd851ae18bd2e0f84c9de59df7a514
https://conda.anaconda.org/conda-forge/linux-64/cudnn-7.6.5.32-h01f27c4_1.tar.bz2#298362896ec792e4a73d59dea331c999
```

**Comment by mariusvniekerk** [comment]
Ah this is the virtual package stuff.   @wolfv thoughts?

**Comment by wolfv** [comment]
you can override virtual packages with env vars (at least in micromamba):

CONDA_OVERRIDE_CUDA=10.3 etc.

https://github.com/mamba-org/mamba/blob/81a490a046b1e1c0093c98f76803b75375e17628/src/core/virtual_packages.cpp#L52-L55

**Comment by wolfv** [comment]
same for glibc, linux, win etc.

**Comment by hajapy** [comment]
Is this something the caller of conda-lock should be concerned with or should it somehow be handled by conda-lock transparently (eg: by adjusting these env vars as it solves for different platforms)?

As a caller, I'd probably have to split my single call to lock multiple platforms into multiple calls with adjusted env vars?

**Comment by wolfv** [comment]
Yeah it really depends if you know what OS config you're targeting... but it would be good if conda-lock could handle these overrides

**Comment by mariusvniekerk** [comment]
So conda-lock could generate a dynamic channel with the required virtual packages present.  

Users will almost certainly want a way to affect this though as you would like to be able to say something like

```
conda-lock --virtual-pacakges virtual_packages.yml --platform linux-64 --platform osx-64
```

with a configuration like the following?

```yaml
# virtual_packages.yml
- subdir: linux-64
  packages:
     __glibc: [2.17]
     __cuda: [11.0]
```

This would allow users to still specify the required constraints that are specific to the hardware that they intend to deploy on.

As a fallback we could just use the full fake virtual package stuff that is present in https://github.com/regro/cf-scripts/blob/e9e2ea7fcd22b7fd23714406505b397e5c5b7954/conda_forge_tick/mamba_solver.py#L448 to allow all solutions.  If users need special portions they would need to add the virtual package requirements to their `environment.yml` as proceed as regular)

conda-lock will then strip these virtual packages our of the ultimate solve when writing out the lockfile.

**Comment by wolfv** [comment]
I think your yaml spec looks nice. Maybe ship with some default version of that? Or a warning? Or maybe print the default overrides for each (simulated) platform so that users clearly see what's going on.
