### ISSUE TITLE
Misleading name "lock"

### ISSUE THREAD

**Issue by epruesse** [conda-incubator/conda-lock#118]
Just my $0.02, but I would strongly suggest to use a different term than "lock" to avoid confusion. 

When I see `conda lock something`, I expect that until I issue `conda unlock something`, modification of `something` is restricted, either to only me or to no-one at all. When I see `somefile.lock` I expect that `somefile` is not allowed to be modified until `somefile.lock` is deleted by the process that created it. Worse, I might to a `find -name \*.lock -delete` after a crash to remove leftover lock files. 

I like the idea - previously I have always installed environments and then exported them to achieve a similar effect. But perhaps some name around "feezing" environments rather than "locking" them wouldn't elicit as much association with "synchronization of concurrent processes"?

**Comment by epruesse** [comment]
All right. Updating my internal jargon dict. ;-)

**Comment by ocefpaf** [comment]
The term issue implies that a non-issue exists. I guess that this was one of those. (Sorry, I couldn't resist.)

Jokes aside, while I don't believe it belongs on conda-lock, it would be an interesting exercise to create a "unlock" command that re-creates the environment.yaml by having only the minimum amount of packages necessary to create the lock, all unpinned.
