### ISSUE TITLE
[Question] Current status of PEP 621 metadata support, usage with PDM

### ISSUE THREAD

**Issue by leroyvn** [conda-incubator/conda-lock#133]
The docs say Flit metadata is supported: does this also cover the new metadata format (PEP 621)?

Also, I'm interested in using conda-lock to create lock files from a PDM project file; I assume I'd also have to add extra logic to parse PDM-specific extra dev dependencies?

**Comment by mariusvniekerk** [comment]
Pep 621 should be supported.

To parse additional kinds of files you would need to add a new format to convert that to the intermediate conda lock spec format that conda lock uses

**Comment by leroyvn** [comment]
Thanks for you answer @mariusvniekerk! 

Just in case it would be something original to PDM, btw: it uses the PEP 621 `project.dependencies` and `project.optional-dependencies` tables, but also has an extra [`tool.pdm.dev-dependencies`](https://pdm.fming.dev/usage/dependency/#add-development-only-dependencies) table allowing to declare dependencies which won't be in the distribution metadata.

I just took a look at the code on the latest `master`. If I understand correctly, I'd have to implement a function similar to `pyproject_toml.py::parse_poetry_pyproject_toml()` or `pyproject_toml.py::parse_pyproject_toml()` adding the extra logic required to collect the dependencies declared in PDM's `dev-dependencies` table, right?
