### ISSUE TITLE
A similar project to conda-lock for the meta.yaml file

### ISSUE THREAD

**Issue by H0R5E** [conda-incubator/conda-lock#136]
Hi, thanks for producing this package, it is very useful. I would like to be able to have similar control to lock the dependencies in the `meta.yaml` file of a conda recipe (rather than generate a lock file from it), do you know if such a project exists?

**Comment by jaimergp** [comment]
`conda-build` ships the `conda render` command, which does precisely this afaik. Also, a built package will contain the rendered recipe in its `info` directory.

**Comment by H0R5E** [comment]
@jaimergp, thanks for the info. I had a quick play with `conda render` and it doesn't seem to define explicit versions for the requirements in my `meta.yaml` file:

```
requirements:
  host:
    ...
  run:
    - jinja2
    - shapely
    - xarray >=0.20.1,!=0.21.0
    - numpy >=1.21
    - scipy
    - python >=3.9.9,<3.10
    - pyyaml
    - netCDF4
    - tabulate
    - pandas
    - geopandas-base
    - brotlipy

**Comment by mariusvniekerk** [comment]
In general though libraries tend not to be equality pinned. The conda lock file is more for making an application environment. 

Conda lock can already generate a lockfile from an existing meta.yaml if you want to use that to make a reproducible test environment or something similar.

**Comment by H0R5E** [comment]
@mariusvniekerk, thanks. Basically, I'm frustrated by packages breaking due to dependency updates. I use conda recipes to deliver applications to my customer, so for them to be so fragile is very annoying. It seems to me that projects like poetry afford some pinning of dependencies to allow stable recreation, but there does not seem to be the same functionality for conda recipes.

**Comment by mariusvniekerk** [comment]
If you want to contribute a new target output format it can probably work for that case.

Conda lock already supports the conda env target so this is not very different. The hard part is that manipulating conda recipes in code is rather tricky.  A tool like souschef would likely be handy for doing that properly.

**Comment by H0R5E** [comment]
@mariusvniekerk, thanks, I will have a look. I will close this now, thanks for your time.
