### ISSUE TITLE
Documented basic usage in README out of sync with released pypi version (0.13.2)

### ISSUE THREAD

**Issue by scottyhq** [conda-incubator/conda-lock#138]
The unified lockfile and pip support enabled by https://github.com/conda-incubator/conda-lock/pull/124 is really convenient! 

Is there a timeline for a new release on pypi? Currently following the README 'basic usage' documentation doesn't work unless you install conda-lock directly from github (pip install git+https://github.com/conda-incubator/conda-lock.git@main)

**Comment by ocefpaf** [comment]
We need to figure out if the issue in https://github.com/conda-incubator/conda-lock/pull/147 is a blocker or not for a new release.

**Comment by wesleykendall** [comment]
Just wanted to chime in and say that the unified pip support is incredible too. I tried the README before I stumbled on this thread and realized it wasn't released.

@ocefpaf it looks like that PR is merged. If you don't mind me asking, should I plan on a direct install for the foreseeable future, or is the 1.0 PyPI release imminent?

**Comment by ocefpaf** [comment]
Version 1.0.1 is already on PyPI and conda-forge. Please try it out!
