### ISSUE TITLE
lock-file should expose md5 and sha256 hashes

### ISSUE THREAD

**Issue by asford** [conda-incubator/conda-lock#141]
@jvansanten This is probably closest to a feature request for your work. I'm happy to implement if the project is +1.

References:
https://github.com/mamba-org/mamba/issues/1209
https://github.com/conda-incubator/conda-lock/pull/131

The not-yet-released conda-lock file format should support specification of package hashes in multiple hash formats,
encompassing (at least) the `md5` and `sha256` has formats potentially available in upstream package metadata.

This will be extremely useful to allow forward-compatibility in the lock format as `conda`/`mamba` evolve, and allow additional tools to interpret the generated locks.

As a motivating example, mentioned in https://github.com/conda-incubator/conda-lock/pull/131, having both the `sha256` and `md5` has available allows tools to fetch and cache packages by the "more common" `sha256` while allowing explicit lock spec generation using the `md5` hash. 

As a specific motivating example, our company maintains an internal tool very similar to conda-lock that maps conda environments to bazel build targets. As we're using bazel to fetch the locked packages, we must specify them as [`http_file`](https://docs.bazel.build/versions/main/repo/http.html#http_file) targets with sha256.

As a strawman, I would propose changing the `hash` field from a string:

```
hash: md5:deadbeef
```

to an explicit mapping of hash algorithms to hashes:

```
hash:
    md5: deadbeef
    sha256: c0wafaba
```

These values would be populated from the upstream package metadata, which must provide md5 and may provide sha256.

In cases where an upstream sha256 is not available it would not be included in the mapping, or _could_ be backfilled by conda-lock by inspection of the package post-lock.

Ie:

```
hash:
    md5: deadbeef
```

is valid output.

**Comment by mariusvniekerk** [comment]
Thanks for taking this one @jvansanten !

I think once this gets in we can should do a release of the version with the new lockfile format.  

This delay would prevent the situation where there are two new combined lockfile format essentially at launch.

**Comment by mariusvniekerk** [comment]
Started on this in #146
