### ISSUE TITLE
Question about explicit lock files with pip

### ISSUE THREAD

**Issue by wesleykendall** [conda-incubator/conda-lock#161]
First off, I cannot begin to describe how great this tool is. Thanks!

I'm using main @ 4203aef6159093b33382018c54e93c58e488ddb5 for this since I really wanted to try out the new pip dependency features.

I did `conda-lock -f pyproject.toml -k explicit`, and I noticed it adds pip requirements in comments:

```
# pip chardet @ https:/.....
```

When I do `conda create --name <name> --file conda-osx-64.lock`, none of the pip requirements are installed.

Do the explicit lock files not support pip? Normally I'd assume a comment is ignored, but I thought I'd at least ask just in case I'm missing something.

Note - I used the main locking format just fine. I was mostly testing this out to see if there's a way other users can install from a lock file without having to first install `conda-lock`. My understanding is that only `conda-lock` can install from the default lock file format.

Again, thank you so much. I cannot believe how easily this all fits in with a poetry project I already had

**Comment by mariusvniekerk** [comment]
The explicit files can be installed using, conda lock can understand the magic comments 

```
conda lock install explicit.lock
```

**Comment by wesleykendall** [comment]
Thanks! I figured that was the case
