### ISSUE TITLE
Long term support for explicit lockfile

### ISSUE THREAD

**Issue by thomasjpfan** [conda-incubator/conda-lock#178]
In the [explicit lockfile docs](https://conda-incubator.github.io/conda-lock/output/#explicit-lockfile), it states that the explicit lockfile is a legacy format. Does conda-lock expect to support this lockfile format in the future?

**Comment by mariusvniekerk** [comment]
So this format will be supported as a render target for at least as conda install supports that means of installation.

Ideally the rendered explicit locks should only be temporary artifacts (this is how conda-lock install actually performs rms installs).

The preferred file to check into source control would be the new unified lockfile.

The explicit lock format is still very handy for docker based use cases

**Comment by thomasjpfan** [comment]
Thanks for the information!
