### ISSUE TITLE
Dependencies of the form channel::name not handled correctly

### ISSUE THREAD

**Issue by rhkleijn** [conda-incubator/conda-lock#188]
In this trimmed down environment.yml file I try to install a particular package from a specific channel.

```
name: tmp
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.10  
  - conda-forge::wrapt  # in this example we prefer the conda-forge version of the package
platforms:
  - linux-64
```

Running conda-lock produces a conda-lock.yml file containing this line
```
  url: https://conda.anaconda.org/anaconda/linux-64/wrapt-1.13.3-py310h7f8727e_2.tar.bz2
```
instead of a url pointing to somewhere in the conda-forge repo.

It does works correctly with conda itself. E.g. running 

```
$ conda env create --file environment.yml --dry-run
```
has in its output this line

```
  - conda-forge/linux-64::wrapt==1.14.0=py310h5764c6d_1
```

**Comment by mariusvniekerk** [comment]
Your channel order is almost certainly going to cause you a whole bunch of issues here.  Mixing the `anaconda` channel with almost any other channel is discouraged
