### ISSUE TITLE
Making the location of PyPI/Conda package mapping file configurable

### ISSUE THREAD

**Issue by skumagai** [conda-incubator/conda-lock#205]
Hi,

I don't have access to Github at work as my environment is behind a corporate firewall that blocks github.com/githubusercontent.com. This poses a problem when my environment.yml contains some pip-based dependencies. 

If I understand correctly, get_forward_lookup (in lookup.py) tries to download a mapping file from a hardcoded URL, which is on githubusercontent.com. conda-lock fails because of that.

Can you make the location of the mapping file configurable (as noted in a todo comment on line 10)? If it is configurable, I can host the file by mirroring regro/cf-graph-countyfair inside of my organization to make it available.

I'm willing to work on this if you can give me some pointers (such as preference on env var vs command line argument).

**Comment by rphel** [comment]
Hello, we also encounter issues when using conda-lock in private network with no access to github.com.

A configurable location can be a good improvement, but this will not really help in our case as we cannot mirror github.com. Is it possible to have a different implementation that look for Pypi package without this lookup table?

**Comment by skumagai** [comment]
Given my inability to access the Internet is due to my development environment, wouldn't it make sense to also handle this as an environment variable (or in a configuration file)?
