### ISSUE TITLE
Missing -p option for conda-lock render

### ISSUE THREAD

**Issue by maresb** [conda-incubator/conda-lock#227]
The "Basic Usage" section of the README includes the command

```bash
conda-lock render -p linux-64
```

but when I run it I get

```bash
Error: No such option: -p
```

**Comment by riccardoporreca** [comment]
@maresb, which version of conda-lock are your using? This seems a duplicate of #169, which was fixed via #193 in v1.1.0

**Comment by maresb** [comment]
@riccardoporreca thank you, I confirm that in an updated environment it works as expected.

I have so many environments that I'm not sure which one I was using. I thought it was up-to-date, but clearly I was mistaken. Also I'm not sure how I missed #169. Sorry for the noise.
