### ISSUE TITLE
Straighten out Poetry dependency chaos

### ISSUE THREAD

**Issue by maresb** [conda-incubator/conda-lock#235]
I wonder if we need to depend on Poetry as a required dependency, since it shouldn't be necessary unless there's a `pip: [...]` section, right?

Poetry finally released a "stable" v1.2 a few days ago, but unfortunately not all is well. There are two blockers which currently make a conda-forge release impossible: 1. it contains a circular dependency with `poetry-plugin-export` which makes conda balk, and 2. there is no stable release of its dependency cleo v1.0.

In terms of testing, it's possible to install Poetry v1.2 / Cleo from conda-forge via dev labels.

In the meantime I've gotten fed up with Poetry, and discovered Hatch, which I like much better. (But it seems we are only using Poetry for its PyPI dependency solver, which Hatch doesn't have.) Currently I can't simultaneously install Poetry 1.1 and Hatch since they have [incompatible pins](https://github.com/pypa/hatch/issues/449) for the `packaging` dependency, and this means that I cannot simultaneously use recent versions of conda-lock with Hatch. :disappointed: 

So I have two questions:

1. Can we turn Poetry into an optional dependency?
2. How much must be changed here in conda-lock in order to accommodate Poetry v1.2?

**Comment by maresb** [comment]
I was thinking that a good solution may be to cut out and vendor just the solver portion of Poetry which is needed by conda-lock. That would hopefully make things much more lightweight.

**Comment by mariusvniekerk** [comment]
The other approach would be to make another pip resolver using the one from pip-tools (invocation here https://github.com/jazzband/pip-tools/blob/master/piptools/scripts/compile.py#L488-L499)

**Comment by maresb** [comment]
Thanks for the tip!

I have not yet in the slightest understood these abstractions. I'll have a look and try to understand what's involved.

**Comment by mariusvniekerk** [comment]
> * Can we turn Poetry into an optional dependency?
It already IS an optional dependency

**Comment by mariusvniekerk** [comment]
If you want to rework the setup stuff to use `hatch` + `build` that would be fantastic

**Comment by maresb** [comment]
Yes, great idea! How do you feel about tiangolo's Typer for CLI? (It's like Click the style of FastAPI with runtime type checking and Pydantic.)

**Comment by mariusvniekerk** [comment]
Given that we already depend on both click and pydantic, all for that

**Comment by maresb** [comment]
I feel like I successfully set up a default subcommand in Typer sometime in the past. But I'll verify that before I sink too much time. Thanks!

**Comment by maresb** [comment]
I've been really annoyed lately when I get some unexpected result and type `conda-lock --version` and get an unrecognized command error. :smile:

**Comment by maresb** [comment]
Perhaps this deserves its own issue, but Poetry 1.1 depends on `clikit` which we left as an implicit dependency even though we use it explicitly. But now that Poetry 1.2 has been released, `clikit` is no longer a dependency of Poetry, so it causes a missing import. 

Fixed as part of https://github.com/conda-incubator/conda-lock/pull/239
