### ISSUE TITLE
[Feature] Detect up-to-date vs stale lock files

### ISSUE THREAD

**Issue by alanhdu** [conda-incubator/conda-lock#24]
One feature that it'd be great to supprt would be fore `conda-lock` to detect when the `environment.yml` has/hasn't changed compared to the generated `.lock`files. That way, for instance, we can cheaply check that the `.lock` file is up-to-date without having to invoke the conda SAT solver again.

One  way to do this would be to embed the hash of `environment.yml` into the lock file (it looks like the lock file supports comments, so we could probably do something there) -- that way, either `conda-lock` (or an external program) could just check the `environment.yml` against the hash to see there's been a change.

If that sounds good, I'd be happy to implement adding the hash to the `.lock` files as a comment, although I'm not sure what the best UI for this feature would be.

**Comment by mariusvniekerk** [comment]
That sounds reasonable, worth taking a stab at.

**Comment by alanhdu** [comment]
Hi @mariusvniekerk! Sorry for the very long delay here.

At work, we've been talking about improving our internal development environment setup, which depend heavily on conda environment. We've come up with a list of things we'd like to improve, but wanted to know whether you'd be open to us contributing some (potentially quite large) changes to `conda-lock`, or whether you'd prefer we build on top of what `conda-lock` (while potentially contributing "small" changes).

I guess another way of phrasing this is whether you would like to keep `conda-lock` as a "light-weight library", or would you be open to adding features that make it a more full-fledged environment manager?

<details>
<summary> List of features </summary>
- Exactly pin down the environments across Mac, Windows, Linux (`conda-lock` does this well!)
- Warn/error if the `environment.yml` was updated while the corresponding lockfile(s) have not been.
- Be able to "diff" the current environment and a lock file and install/remove only the changes (otherwise, very large environments take a long time to install/modify)
- The ability to have multiple related but distinct environments (e.g. GPU vs CPU environments,, or a run environment that is a subset of a development environment)
</details>

**Comment by mariusvniekerk** [comment]
Those sound like really good changes and I'd be excited to see what you come up with.

Ideally we can maintain compatibility with the conda env file if possible, but if we need to extend that we can do that too (potentially up streaming those changes into conda)

**Comment by mariusvniekerk** [comment]
Cc @ocefpaf @scopatz

**Comment by scopatz** [comment]
CC @costrouc

**Comment by mariusvniekerk** [comment]
This is now supported via the `--check-input-hash` feature added in #104
