### ISSUE TITLE
`conda-lock update` not updating

### ISSUE THREAD

**Issue by jesshart** [conda-incubator/conda-lock#248]
When using the `conda-lock --update` feature, I cannot get it to update `python` from `3.8` to `3.9`. Am I doing something silly here or is this unexpected behavior? See the command vs. what is after `...using specs...`.

```bash
(base) conda-lock --update python=3.9
Locking dependencies for ['linux-64', 'osx-64', 'win-64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['python 3.8.*']
INFO:conda_lock.conda_solver:osx-64 using specs ['python 3.8.*']
```

When I check the `conda-lock.yml` file, I see that no update has been made.

**Comment by jesshart** [comment]
I found a connection to why this was happening. My `environment.yml` file still specified `python=3.8` which must have taken precedence over my command to update. I am still not sure if this is expected behavior, but it is at least explainable.

When I remove the pinned version from `environment.yml` (i.e., `python=3.9` -> `python`) the command follows suit,
```bash
(base) conda-lock --update python=3.9
Locking dependencies for ['linux-64', 'osx-64', 'win-64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['python']
```
I suppose the best way to do this would be to update the `environment.yml` file and then run the update command.

**Comment by mariusvniekerk** [comment]
yep thats the better approach
