### ISSUE TITLE
`--auth-file` contents are not used for `conda-lock install`

### ISSUE THREAD

**Issue by simonbohnen** [conda-incubator/conda-lock#270]
There's a typo in the `install` command, we should check for the combined `_auth` object instead of looking only at the value of the `auth` flag:

https://github.com/conda-incubator/conda-lock/blob/04e24386914158e10f6c60084655fdf207df008d/conda_lock/conda_lock.py#L1268-L1270

https://github.com/conda-incubator/conda-lock/blob/04e24386914158e10f6c60084655fdf207df008d/conda_lock/conda_lock.py#L1284-L1286

**Comment by maresb** [comment]
Thanks!!! Do you have the time to make a PR for this?

**Comment by simonbohnen** [comment]
Done!
