### ISSUE TITLE
support platform linux-arm64

### ISSUE THREAD

**Issue by daeh** [conda-incubator/conda-lock#284]
Currently lock files support osx-arm64, but not linux-arm64.

This causes multiple issues. For example: trying to use a `linux-64` lock file with a `arm64` docker (e.g. `arm64v8/debian:bullseye`) causes the python environment to fail. To use lock files with docker images, the image needs to be built for amd64, which is incredibly slow to run on arm64 systems. 

Will it be possible support linux-arm64?

**Comment by maresb** [comment]
Hi @daeh, linux-arm64 is actually supported by Conda-Forge under the rather [esoteric](https://stackoverflow.com/a/47274698/10155767) name `linux-aarch64`.

I'm not sure where is the list of conda-forge supported platforms is maintained, but perhaps it would be clever to add a comprehensive list to the README...

Enjoy the speed! :wink: :rocket:

**Comment by maresb** [comment]
See #286

**Comment by daeh** [comment]
amazing. I got confused by docs elsewhere that made me think aarch64 and arm64v8 were different in some subtle but important way, but aarch64 is working great with the arm64 docker image. Thanks for clearing up my misunderstanding!

**Comment by maresb** [comment]
@daeh no worries, and it's not just you, I was confused about the same point myself! (That's how I knew the answer right away.)
