### ISSUE TITLE
Update existing conda env not supported

### ISSUE THREAD

**Issue by yonil7** [conda-incubator/conda-lock#305]
Currently `conda-lock install ...` cant be used for updating existing conda env.
This seems to be because under the hood, it calls `mamba create` / `conda create` instead of calling `mamba update` / `conda update`
I think this can be fixed by changing this line: https://github.com/conda-incubator/conda-lock/blob/4f073003bf9563a93d4c617e7272d629198b33ed/conda_lock/conda_lock.py#L221
from `"create"` to `"update"`

**Comment by mariusvniekerk** [comment]
This is intentional.  Mutation of environments is fraught with numerous issues.

**Comment by yonil7** [comment]
Thanks.
What should be the recommended practice for the following development process:

1. In our group each one have a development env `devenv` on his/her laptop
2. We have a single conda-lock file that we keep in git and update it from time to time with new dependencies
3. Once its updated, all the group update their `devenv` accordingly. (before we used `conda-lock` we did this using `mamba update`)

**Comment by mariusvniekerk** [comment]
The recommended approach is to just delete that env and recreate it

**Comment by ctcjab** [comment]
I think this is worth a small update to the docs and `--help` output. Something along the lines of just:

> To update an existing environment from an updated lockfile, you can remove and re-create the environment, or better yet, just re-run `conda-lock install -n existing`, which automates this for you.
