### ISSUE TITLE
Performance relative to conda update yaml

### ISSUE THREAD

**Issue by kev-zheng** [conda-incubator/conda-lock#51]
We'd like to take advantage of fully reproducible lockfiles for our conda environments, but are experiencing 2-4 minute performance regressions depending on our machine. Is this expected behavior / are other users experiencing this issue with conda update via lockfile versus environment yaml file?

**Comment by mariusvniekerk** [comment]
How are you using conda lock? In general installing from a lock should be much faster than doing a solve.

If you regenerate the lockfiles every time it will be slower.
