### ISSUE TITLE
`<TOKEN>` in private repo package urls

### ISSUE THREAD

**Issue by sanzoghenzo** [conda-incubator/conda-lock#70]
Hi, first of all many thanks for this great utility!

I'm trying to use it to lock an environment that contains a couple of package published on my private conda repository (quetz);
in my machine I can install them my first adding the channel with the `/t/my-token/` before the channel endpoint;

```shell
conda config --add channels https://my-repo,com/t/my-token/channels/stable
```

I also have an environment.yaml with the channel and the token specified, until [conda#10018](https://github.com/conda/conda/issues/10018) is solved, and i can create the environment with it.

creating a lock file from this environment.yml, the urls for the packages in my repo are like `https://my-repo.com/t/<TOKEN>/channels/stable/noarch/my-package`, and if I try to create an environment from it I obviously get a `401 unauthorized` error.

Is this somewhat intended? should I use some env var to set the token?
Or is it that the case of private repos is not handled?

**Comment by mariusvniekerk** [comment]
If there is a canonical environment variable used for the token, we can add some support for that

**Comment by sanzoghenzo** [comment]
I didn't find any canonical envvar in the conda documentation.
quetz-client has its own `QUETZ_API_KEY`, but it's not used by other tools.

I honestly don't know if there's an elegant solution for this, since putting the token in environment.yml or lockfile and then committing them to a repo is definitely a bad practice.

Speaking of which, I tried to remove the channel from the environment.yml; since I have it (with the token) in my condarc file, `conda create` works ok, but this completely breaks conda-lock because it can't find the packages.

**Comment by mariusvniekerk** [comment]
Does conda env parse environment variables for its channels? If so we could support it

**Comment by sanzoghenzo** [comment]
no, from what I understood it uses the channels specified in both the `environment.yml` and the `~/.condarc` file (both can have a `channels` section):.
The latter can hold the full url with the token (the part between the `/t/` and the next `/`) without the security issues described.

but I still don't know how `conda create --file` works exactly... I'll check if it can add the token form the .condarc if it finds a matching url in the conda lock (that is, without the `/t/<my-token>` part).

**Comment by sanzoghenzo** [comment]
ok, I've removed the `channels` section in my `environment.yml` so that the `--override-channels` option is not added and the lockfile is created based on my `.condarc`.
This is fine for me because I will also use an injected `.condarc` in my CI/CD and no secrets are exposes via git.

The problem with the lock file persist, though. I still get the `/t/<TOKEN>` string in the url of my repo packages.

I also tried to remove this substring, but `conda create` still reports the unauthorized error.

At this point I think the problem lies within `conda create --file` that doesn't handle the <TOKEN> based on the channels in `.condarc`.

thanks for your support, It seems that no changes are needed after all.

**Comment by sanzoghenzo** [comment]
Oh, wait, if I remove/comment the `@EXPLICIT` line and remove the `/t/<TOKEN>` occurrences, it seems to work!

This is because @EXPLICIT forces conda to take the line as is, no other manipulations are performed.

So a quick and dirty way to solve this is to check if there are urls with the  `/t/<TOKEN>` substring, remove the substring and skip the `@EXPLICIT` line.

Can it be done?

**Comment by mariusvniekerk** [comment]
Removing the explicit means you invoke the solver again which means you're not guaranteed to install the packages present in the lock.

**Comment by sanzoghenzo** [comment]
You're right, I opened an issue in conda to support the token expansion. 🤞

**Comment by mariusvniekerk** [comment]
This is now supported in main.  Handled by #156
